/**
 * Premium xidmət ikonları (2026-08-13) — ChatGPT-də yaradılıb, vahid tünd
 * fona normallaşdırılıb (gpt-image-1 edits), Vercel Blob-da saxlanılır.
 *
 * 2026-08-21: mənbə fayllar PNG-dən WebP-ə keçirildi (768px, q82) — 227 MB
 * → 18 MB (~12.5×). Orijinal .png-lər Blob-da SİLİNMƏYİB; nəsə pozularsa
 * aşağıdakı uzantını .png-ə qaytarmaq kifayətdir. Çevirmə skripti:
 * scripts/icons-to-webp.mts.
 * DB-yə YAZILMIR (baza canlı saytla ortaqdır; canlı köhnə dizayndadır) —
 * demo mərhələsində xəritə kod tərəfindədir. Tam seriya hazır olanda
 * Service.iconUrl-ə köçürülə bilər.
 */
const BLOB = "https://e0laauvwfyekwbiy.public.blob.vercel-storage.com/service-icons";

export const SERVICE_ICON_URLS: Record<string, string> = {
  "bud-rentgeni": `${BLOB}/bud-rentgeni.webp`,
  "diz-rentgeni": `${BLOB}/diz-rentgeni.webp`,
  "baldir-rentgeni": `${BLOB}/baldir-rentgeni.webp`,
  "topuq-rentgeni": `${BLOB}/topuq-rentgeni.webp`,
  "ayaq-rentgeni": `${BLOB}/ayaq-rentgeni.webp`,
  "ayaq-barmaqlari-rentgeni": `${BLOB}/ayaq-barmaqlari-rentgeni.webp`,
  "daban-rentgeni": `${BLOB}/daban-rentgeni.webp`,
  "kelle-rentgeni": `${BLOB}/kelle-rentgeni.webp`,
  "burun-sumukleri-rentgeni": `${BLOB}/burun-sumukleri-rentgeni.webp`,
  "uz-sumukleri-rentgeni": `${BLOB}/uz-sumukleri-rentgeni.webp`,
  "goz-yuvasi-orbita-rentgeni": `${BLOB}/goz-yuvasi-orbita-rentgeni.webp`,
  "alt-cene-rentgeni": `${BLOB}/alt-cene-rentgeni.webp`,
  "ust-cene-rentgeni": `${BLOB}/ust-cene-rentgeni.webp`,
  "boyun-rentgeni": `${BLOB}/boyun-rentgeni.webp`,
  "boyun-feqereleri-rentgeni": `${BLOB}/boyun-feqereleri-rentgeni.webp`,
  "boyun-yumsaq-toxumalarinin-rentgeni": `${BLOB}/boyun-yumsaq-toxumalarinin-rentgeni.webp`,
  "bazu-rentgeni": `${BLOB}/bazu-rentgeni.webp`,
  "kurek-sumuyu-rentgeni": `${BLOB}/kurek-sumuyu-rentgeni.webp`,
  "ciyin-rentgeni": `${BLOB}/ciyin-rentgeni.webp`,
  "canaq-rentgeni": `${BLOB}/canaq-rentgeni.webp`,
  "omba-oynagi-rentgeni": `${BLOB}/omba-oynagi-rentgeni.webp`,
  "sakroiliak-oynaq-rentgeni": `${BLOB}/sakroiliak-oynaq-rentgeni.webp`,
  "paranazal-sinuslarin-rentgeni": `${BLOB}/paranazal-sinuslarin-rentgeni.webp`,
  "temporomandibulyar-oynaq-tmj-rentgeni": `${BLOB}/temporomandibulyar-oynaq-tmj-rentgeni.webp`,
  "mastoid-rentgeni": `${BLOB}/mastoid-rentgeni.webp`,
  "barmaq-rentgeni": `${BLOB}/barmaq-rentgeni.webp`,
  "bilek-rentgeni": `${BLOB}/bilek-rentgeni.webp`,
  "el-rentgeni": `${BLOB}/el-rentgeni.webp`,
  "dirsek-rentgeni": `${BLOB}/dirsek-rentgeni.webp`,
  "bud-dexa": `${BLOB}/bud-dexa.webp`,
  "bel-dexa": `${BLOB}/bel-dexa.webp`,
  "tam-beden-dexa": `${BLOB}/tam-beden-dexa.webp`,
  "sumuk-mineral-sixligi-olculmesi-dexa": `${BLOB}/sumuk-mineral-sixligi-olculmesi-dexa.webp`,

  // 2026-08-16 seriyası (40): dental tomoqrafiya, floroskopiya, KT — etiket
  // yazıları bağlı-komponent analizi ilə silinib, şəffaf fon, 1024 kvadrat.
  "3d-tomoqrafiya-alt-cene": `${BLOB}/3d-tomoqrafiya-alt-cene.webp`,
  "3d-tomoqrafiya-ust-cene": `${BLOB}/3d-tomoqrafiya-ust-cene.webp`,
  "3d-tomoqrafiya-tam-uz": `${BLOB}/3d-tomoqrafiya-tam-uz.webp`,
  "3d-tomoqrafiya-hissevi": `${BLOB}/3d-tomoqrafiya-hissevi.webp`,
  "3d-tomoqrafiya-alt-ust-cene": `${BLOB}/3d-tomoqrafiya-alt-ust-cene.webp`,
  "cbct": `${BLOB}/cbct.webp`,
  "implant-tomoqrafiya": `${BLOB}/implant-tomoqrafiya.webp`,
  "cerrahi-sablon-dizayni": `${BLOB}/cerrahi-sablon-dizayni.webp`,
  "cerrahi-sablon-capi": `${BLOB}/cerrahi-sablon-capi.webp`,
  "tmj-aciq-agizla": `${BLOB}/tmj-aciq-agizla.webp`,
  "tmj-qapali-agizla": `${BLOB}/tmj-qapali-agizla.webp`,
  "burunetrafi-ve-alin-ciblerin-kt-si": `${BLOB}/burunetrafi-ve-alin-ciblerin-kt-si.webp`,
  "agiz-ici-intraoral-skan": `${BLOB}/agiz-ici-intraoral-skan.webp`,
  "dental-rentgen": `${BLOB}/dental-rentgen.webp`,
  "panoramik-rentgen": `${BLOB}/panoramik-rentgen.webp`,
  "sefalometrik-rentgen": `${BLOB}/sefalometrik-rentgen.webp`,
  "sefalometrik-rentgen-analiz-daxil": `${BLOB}/sefalometrik-rentgen-analiz-daxil.webp`,
  "agil-disi-rentgeni": `${BLOB}/agil-disi-rentgeni.webp`,
  "ortodontiya-rentgeni": `${BLOB}/ortodontiya-rentgeni.webp`,
  "cene-sumuyu-analizi": `${BLOB}/cene-sumuyu-analizi.webp`,
  "sinus-cene-anatomiyasi": `${BLOB}/sinus-cene-anatomiyasi.webp`,
  "qida-borusunun-kontrast-muayinesi": `${BLOB}/qida-borusunun-kontrast-muayinesi.webp`,
  "mede-bagirsaq-kontrast-muayinesi": `${BLOB}/mede-bagirsaq-kontrast-muayinesi.webp`,
  "barium-udma-testi": `${BLOB}/barium-udma-testi.webp`,
  "histerosalpinqoqrafiya-hsg": `${BLOB}/histerosalpinqoqrafiya-hsg.webp`,
  "venoqrafiya": `${BLOB}/venoqrafiya.webp`,
  "fistuloqrafiya": `${BLOB}/fistuloqrafiya.webp`,
  "bas-kt": `${BLOB}/bas-kt.webp`,
  "beyin-kt": `${BLOB}/beyin-kt.webp`,
  "sinus-kt": `${BLOB}/sinus-kt.webp`,
  "temporal-sumuk-kt": `${BLOB}/temporal-sumuk-kt.webp`,
  "boyun-kt": `${BLOB}/boyun-kt.webp`,
  "agciyer-kt": `${BLOB}/agciyer-kt.webp`,
  "qarin-kt": `${BLOB}/qarin-kt.webp`,
  "kicik-canaq-kt": `${BLOB}/kicik-canaq-kt.webp`,
  "onurga-kt": `${BLOB}/onurga-kt.webp`,
  "diz-kt": `${BLOB}/diz-kt.webp`,
  "ayaq-kt": `${BLOB}/ayaq-kt.webp`,
  "el-kt": `${BLOB}/el-kt.webp`,
  "urek-kt": `${BLOB}/urek-kt.webp`,

  // 2026-08-16 seriyası 2 (36): MRT, onurğa, sinə, uşaq, mammoqrafiya, USM.
  "urek-mrt": `${BLOB}/urek-mrt.webp`,
  "bas-mrt": `${BLOB}/bas-mrt.webp`,
  "beyin-mrt": `${BLOB}/beyin-mrt.webp`,
  "hipofiz-mrt": `${BLOB}/hipofiz-mrt.webp`,
  "boyun-mrt": `${BLOB}/boyun-mrt.webp`,
  "bel-mrt": `${BLOB}/bel-mrt.webp`,
  "diz-mrt": `${BLOB}/diz-mrt.webp`,
  "ciyin-mrt": `${BLOB}/ciyin-mrt.webp`,
  "qarin-mrt": `${BLOB}/qarin-mrt.webp`,
  "canaq-mrt": `${BLOB}/canaq-mrt.webp`,
  "koronar-kt-angioqrafiya": `${BLOB}/koronar-kt-angioqrafiya.webp`,
  "boyun-onurgasi-rentgeni": `${BLOB}/boyun-onurgasi-rentgeni.webp`,
  "dos-onurgasi-rentgeni": `${BLOB}/dos-onurgasi-rentgeni.webp`,
  "bel-onurgasi-rentgeni": `${BLOB}/bel-onurgasi-rentgeni.webp`,
  "oma-sakrum-rentgeni": `${BLOB}/oma-sakrum-rentgeni.webp`,
  "quyruq-sumuyu-koksiks-rentgeni": `${BLOB}/quyruq-sumuyu-koksiks-rentgeni.webp`,
  "tam-onurga-rentgeni": `${BLOB}/tam-onurga-rentgeni.webp`,
  "skolioz-rentgeni": `${BLOB}/skolioz-rentgeni.webp`,
  "agciyer-rentgeni": `${BLOB}/agciyer-rentgeni.webp`,
  "dos-qefesi-rentgeni": `${BLOB}/dos-qefesi-rentgeni.webp`,
  "qabirga-rentgeni": `${BLOB}/qabirga-rentgeni.webp`,
  "sternum-dos-sumuyu-rentgeni": `${BLOB}/sternum-dos-sumuyu-rentgeni.webp`,
  "korpucuk-sumuyu-rentgeni": `${BLOB}/korpucuk-sumuyu-rentgeni.webp`,
  "usaq-skelet-rentgeni": `${BLOB}/usaq-skelet-rentgeni.webp`,
  "bud-canaq-skrininqi": `${BLOB}/bud-canaq-skrininqi.webp`,
  "sumuk-yasinin-teyini-bone-age": `${BLOB}/sumuk-yasinin-teyini-bone-age.webp`,
  "reqemsal-mammoqrafiya": `${BLOB}/reqemsal-mammoqrafiya.webp`,
  "skrininq-mammoqrafiyasi": `${BLOB}/skrininq-mammoqrafiyasi.webp`,
  "diaqnostik-mammoqrafiya": `${BLOB}/diaqnostik-mammoqrafiya.webp`,
  "tomosintez-3d-mammoqrafiya": `${BLOB}/tomosintez-3d-mammoqrafiya.webp`,
  "qarin-usm": `${BLOB}/qarin-usm.webp`,
  "tiroid-usm": `${BLOB}/tiroid-usm.webp`,
  "sud-vezi-usm": `${BLOB}/sud-vezi-usm.webp`,
  "doppler-usm": `${BLOB}/doppler-usm.webp`,
  "hamilelik-usm": `${BLOB}/hamilelik-usm.webp`,
  "usaq-usm": `${BLOB}/usaq-usm.webp`,

  // 2026-08-16 son 2 — kataloq TAM (111 aktiv xidmətin hamısında ikon;
  // "3d-tomoqrafiya" generiki istifadəçi qərarı ilə deaktiv edildi).
  "usaqlarda-skolioz-rentgeni": `${BLOB}/usaqlarda-skolioz-rentgeni.webp`,
  "3d-tomoqrafiya-frontal-nahiyye": `${BLOB}/3d-tomoqrafiya-frontal-nahiyye.webp`,

  // 2026-08-21 seriyası (9): floroskopiya + USM + yeni rentgen xidmətləri
  "yasti-pencelik-rentgeni": `${BLOB}/yasti-pencelik-rentgeni.webp`,
  "said-sumukleri-rentgeni": `${BLOB}/said-sumukleri-rentgeni.webp`,
  "turk-yeheri-rentgeni": `${BLOB}/turk-yeheri-rentgeni.webp`,
  "dos-qefesi-rentgenoskopiyasi": `${BLOB}/dos-qefesi-rentgenoskopiyasi.webp`,
  "irriqoskopiya": `${BLOB}/irriqoskopiya.webp`,
  "ginekoloji-usm": `${BLOB}/ginekoloji-usm.webp`,
  "uroloji-usm": `${BLOB}/uroloji-usm.webp`,
  "limfa-duyunleri-usm": `${BLOB}/limfa-duyunleri-usm.webp`,
  "yumsaq-toxuma-usm": `${BLOB}/yumsaq-toxuma-usm.webp`,

  // 2026-08-21 son 2 — kataloq yenidən TAM (bütün aktiv xidmətlərdə ikon)
  "unvanda-rentgen-xidmeti": `${BLOB}/unvanda-rentgen-xidmeti.webp`,
  "qarin-boslugu-rentgeni": `${BLOB}/qarin-boslugu-rentgeni.webp`,
};
