/**
 * Premium xidmət ikonları (2026-08-13) — ChatGPT-də yaradılıb, vahid tünd
 * fona normallaşdırılıb (gpt-image-1 edits), Vercel Blob-da saxlanılır.
 * DB-yə YAZILMIR (baza canlı saytla ortaqdır; canlı köhnə dizayndadır) —
 * demo mərhələsində xəritə kod tərəfindədir. Tam seriya hazır olanda
 * Service.iconUrl-ə köçürülə bilər.
 */
const BLOB = "https://e0laauvwfyekwbiy.public.blob.vercel-storage.com/service-icons";

export const SERVICE_ICON_URLS: Record<string, string> = {
  "bud-rentgeni": `${BLOB}/bud-rentgeni.png`,
  "diz-rentgeni": `${BLOB}/diz-rentgeni.png`,
  "baldir-rentgeni": `${BLOB}/baldir-rentgeni.png`,
  "topuq-rentgeni": `${BLOB}/topuq-rentgeni.png`,
  "ayaq-rentgeni": `${BLOB}/ayaq-rentgeni.png`,
  "ayaq-barmaqlari-rentgeni": `${BLOB}/ayaq-barmaqlari-rentgeni.png`,
  "daban-rentgeni": `${BLOB}/daban-rentgeni.png`,
  "kelle-rentgeni": `${BLOB}/kelle-rentgeni.png`,
  "burun-sumukleri-rentgeni": `${BLOB}/burun-sumukleri-rentgeni.png`,
  "uz-sumukleri-rentgeni": `${BLOB}/uz-sumukleri-rentgeni.png`,
  "goz-yuvasi-orbita-rentgeni": `${BLOB}/goz-yuvasi-orbita-rentgeni.png`,
  "alt-cene-rentgeni": `${BLOB}/alt-cene-rentgeni.png`,
  "ust-cene-rentgeni": `${BLOB}/ust-cene-rentgeni.png`,
  "boyun-rentgeni": `${BLOB}/boyun-rentgeni.png`,
  "boyun-feqereleri-rentgeni": `${BLOB}/boyun-feqereleri-rentgeni.png`,
  "boyun-yumsaq-toxumalarinin-rentgeni": `${BLOB}/boyun-yumsaq-toxumalarinin-rentgeni.png`,
  "bazu-rentgeni": `${BLOB}/bazu-rentgeni.png`,
  "kurek-sumuyu-rentgeni": `${BLOB}/kurek-sumuyu-rentgeni.png`,
  "ciyin-rentgeni": `${BLOB}/ciyin-rentgeni.png`,
  "canaq-rentgeni": `${BLOB}/canaq-rentgeni.png`,
  "omba-oynagi-rentgeni": `${BLOB}/omba-oynagi-rentgeni.png`,
  "sakroiliak-oynaq-rentgeni": `${BLOB}/sakroiliak-oynaq-rentgeni.png`,
  "paranazal-sinuslarin-rentgeni": `${BLOB}/paranazal-sinuslarin-rentgeni.png`,
  "temporomandibulyar-oynaq-tmj-rentgeni": `${BLOB}/temporomandibulyar-oynaq-tmj-rentgeni.png`,
  "mastoid-rentgeni": `${BLOB}/mastoid-rentgeni.png`,
  "barmaq-rentgeni": `${BLOB}/barmaq-rentgeni.png`,
  "bilek-rentgeni": `${BLOB}/bilek-rentgeni.png`,
  "el-rentgeni": `${BLOB}/el-rentgeni.png`,
  "dirsek-rentgeni": `${BLOB}/dirsek-rentgeni.png`,
  "bud-dexa": `${BLOB}/bud-dexa.png`,
  "bel-dexa": `${BLOB}/bel-dexa.png`,
  "tam-beden-dexa": `${BLOB}/tam-beden-dexa.png`,
  "sumuk-mineral-sixligi-olculmesi-dexa": `${BLOB}/sumuk-mineral-sixligi-olculmesi-dexa.png`,

  // 2026-08-16 seriyası (40): dental tomoqrafiya, floroskopiya, KT — etiket
  // yazıları bağlı-komponent analizi ilə silinib, şəffaf fon, 1024 kvadrat.
  "3d-tomoqrafiya-alt-cene": `${BLOB}/3d-tomoqrafiya-alt-cene.png`,
  "3d-tomoqrafiya-ust-cene": `${BLOB}/3d-tomoqrafiya-ust-cene.png`,
  "3d-tomoqrafiya-tam-uz": `${BLOB}/3d-tomoqrafiya-tam-uz.png`,
  "3d-tomoqrafiya-hissevi": `${BLOB}/3d-tomoqrafiya-hissevi.png`,
  "3d-tomoqrafiya-alt-ust-cene": `${BLOB}/3d-tomoqrafiya-alt-ust-cene.png`,
  "cbct": `${BLOB}/cbct.png`,
  "implant-tomoqrafiya": `${BLOB}/implant-tomoqrafiya.png`,
  "cerrahi-sablon-dizayni": `${BLOB}/cerrahi-sablon-dizayni.png`,
  "cerrahi-sablon-capi": `${BLOB}/cerrahi-sablon-capi.png`,
  "tmj-aciq-agizla": `${BLOB}/tmj-aciq-agizla.png`,
  "tmj-qapali-agizla": `${BLOB}/tmj-qapali-agizla.png`,
  "burunetrafi-ve-alin-ciblerin-kt-si": `${BLOB}/burunetrafi-ve-alin-ciblerin-kt-si.png`,
  "agiz-ici-intraoral-skan": `${BLOB}/agiz-ici-intraoral-skan.png`,
  "dental-rentgen": `${BLOB}/dental-rentgen.png`,
  "panoramik-rentgen": `${BLOB}/panoramik-rentgen.png`,
  "sefalometrik-rentgen": `${BLOB}/sefalometrik-rentgen.png`,
  "sefalometrik-rentgen-analiz-daxil": `${BLOB}/sefalometrik-rentgen-analiz-daxil.png`,
  "agil-disi-rentgeni": `${BLOB}/agil-disi-rentgeni.png`,
  "ortodontiya-rentgeni": `${BLOB}/ortodontiya-rentgeni.png`,
  "cene-sumuyu-analizi": `${BLOB}/cene-sumuyu-analizi.png`,
  "sinus-cene-anatomiyasi": `${BLOB}/sinus-cene-anatomiyasi.png`,
  "qida-borusunun-kontrast-muayinesi": `${BLOB}/qida-borusunun-kontrast-muayinesi.png`,
  "mede-bagirsaq-kontrast-muayinesi": `${BLOB}/mede-bagirsaq-kontrast-muayinesi.png`,
  "barium-udma-testi": `${BLOB}/barium-udma-testi.png`,
  "histerosalpinqoqrafiya-hsg": `${BLOB}/histerosalpinqoqrafiya-hsg.png`,
  "venoqrafiya": `${BLOB}/venoqrafiya.png`,
  "fistuloqrafiya": `${BLOB}/fistuloqrafiya.png`,
  "bas-kt": `${BLOB}/bas-kt.png`,
  "beyin-kt": `${BLOB}/beyin-kt.png`,
  "sinus-kt": `${BLOB}/sinus-kt.png`,
  "temporal-sumuk-kt": `${BLOB}/temporal-sumuk-kt.png`,
  "boyun-kt": `${BLOB}/boyun-kt.png`,
  "agciyer-kt": `${BLOB}/agciyer-kt.png`,
  "qarin-kt": `${BLOB}/qarin-kt.png`,
  "kicik-canaq-kt": `${BLOB}/kicik-canaq-kt.png`,
  "onurga-kt": `${BLOB}/onurga-kt.png`,
  "diz-kt": `${BLOB}/diz-kt.png`,
  "ayaq-kt": `${BLOB}/ayaq-kt.png`,
  "el-kt": `${BLOB}/el-kt.png`,
  "urek-kt": `${BLOB}/urek-kt.png`,
};
