// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Used by the Prisma CLI for migrate/db push. Prefer the direct (non-pooled)
    // connection; fall back to the pooled URL if a direct one isn't provided.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
